bookmark/acc_class/urls.py
from django.urls import path

from .views import AccLogin

app_name = 'acc_class'

urlpatterns = [
    path('login/', AccLogin.as_view(), name='acc_class_login')
]

bookmark/account/urls.py
from django.urls import path, reverse_lazy
from .views import dashboard
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login, PasswordChangeView, \
    PasswordChangeDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView

from .views import user_login

app_name = 'account'

# urlpatterns = [
#     path('login/', user_login, name='login'),
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('login/', LoginView.as_view(template_name='account/registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='account/registration/logout.html'), name='logout'),
    path('logout_then_login', logout_then_login, name='logout_then_login'),
    # change password
    path('password_change/', PasswordChangeView.as_view(success_url=reverse_lazy('account:password_change_done'),
                                                        template_name='account/registration/password_change.html'),
         name='password_change'),
    path('password_change_done/',
         PasswordChangeDoneView.as_view(template_name='account/registration/password_change_done.html'),
         name='password_change_done'),
    # reset password
    path('password_reset/',
         PasswordResetView.as_view(template_name='account/registration/password_reset_form.html',
                                   email_template_name='account/registration/password_reset_email.html',
                                   success_url='done/'),
         name='password_reset'),
    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(template_name='account/registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='account/registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='account/registration/password_reset_confirm.html',
         success_url='/account/password_reset_complete/'),
         name='password_reset_confirm'),

]
# ]

bookmark/bookmark/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('acc_class/', include('acc_class.urls'))
]

bookmark/acc_class/models.py
from django.db import models

# Create your models here.

bookmark/account/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    passwords = forms.CharField(widget=forms.PasswordInput)

bookmark/acc_class/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django import forms


class AccLogin(LoginView):
    # ссылка на наш шаблон
    template_name = 'acc_class/login.html'

    # метод создания формы
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        form = super(AccLogin, self).get_form(form_class)
        form.fields['username'].widget = forms.TextInput(attrs={'placeholder': 'Login'})
        form.fields['password'].widget = forms.PasswordInput(attrs={'placeholder': 'Password'})
        return form

bookmark/account/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from .forms import LoginForm


def user_login(request):
    # проверяем пост запрос, if request 'post'
    if request.method == 'POST':
        # создаем экземпляр формы с данным из post запроса
        form = LoginForm(request.POST)
        # проверяем валидность формы,  если не валидна в шаблоне отображаются ошибки формы
        if form.is_valid():
            # с помощью метода cleaned_data забираем данные из формы
            cln_data = form.cleaned_data
            # метод authenticate() проверяет данные в БД и возвращает нам объект User
            user = authenticate(username=cln_data['username'], password=cln_data['passwords'])
            # проверяем есть ли указнные пользователь
            if user is not None:
                # проверяем активен ли пользователь в БД
                if user.is_active:
                    # c помощью метода login входим в систему,
                    # устанавливаем сессию (session) и возвращаем ответ об удачном входе
                    login(request, user)
                    return HttpResponse('Successfully authenticated!')
                else:
                    # если is_active = False, отвечаем что данный аккаунт не активен
                    return HttpResponse('Login failed, account is disabled!')
            else:
                # если user = None - нет данного юзера в бд
                return HttpResponse('Login failed, user does not exist!')
    else:
        # Если приходит post запрос GET, отрисовываем пустю форму
        form = LoginForm()
    # отображаем нашу Логин страницу login.html, передаем форму form
    return render(request, 'account/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request, 'account/dashboad.html', {'section': 'dashboard'})

bookmark/acc_class/templates/acc_class/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    login
{% endblock %}

{% block content %}
    <h1>Login</h1>
    <p>Please, use this form to login.</p>
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login" class="btn btn-success">
    </form>
{% endblock %}

bookmark/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
    {% endblock %}
</head>
<body>
<div class="container">
    {% block header %}
        {% include 'snippets/menu_snippets.html' %}
        <div class="header">
            {% if request.user.is_authenticated %}
                <ul>
                    <li {% if section == 'dashboard' %} class="selected" {% endif %}>
                        <a href="{% url 'account:dashboard' %}">Dashboard</a>
                    </li>
                    <li {% if section == 'images' %} class="selected" {% endif %} >
                        <a href="#">Images</a>
                    </li>
                    <li {% if section == 'people' %} class="selected" {% endif %} >
                        <a href="#">People</a>
                    </li>
                </ul>
            {% endif %}
            <span class="user">
                {% if request.user.is_authenticated %}
                    hello {{ request.user.first_name }}!
                    <a href="{% url 'account:logout' %}">logout</a>
                {% else %}
                    <a href="{% url 'account:login' %}">Login</a>
                {% endif %}
            </span>
        </div>
    {% endblock %}


    {% block content %}

    {% endblock %}
</div>
</body>
{% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
{% endblock %}
</html>

bookmark/templates/snippets/menu_snippets.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>